nginx:
  image: nginx
  expose:
    - 80
selenium:
  image: selenium/standalone-firefox
  expose:
    - 4444
  links:
    - nginx
webdriver:
  image: node:6
  volumes:
    - .:/app
  working_dir: /app
  links:
    - selenium
    - nginx
  command: ["true"]
